# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'keep4u-IOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for keep4u-IOS

  pod 'OpenAPIClient', :path => 'Vendor'
  pod 'SideMenu'
  pod "RxSwift"
  pod "RxCocoa"
  pod "markymark"

end
